In [1]:
import numpy as np
weights = [1,1,2,2,3]

# Augmented 
samples = np.array([
    [1,0.0, 1.0],
    [1,1.0,0.0],
    [1,0.5,1.5],
    [1,1.0,1.0],
    [1,-0.5,0.0]
    ])

In [2]:
def sequential_multi_class_perceptron_learning_algorithm(weights, samples, learning_rate=1, epochs=1, classes=3):
    # This version of the batch perceptron learning algorithm requires normalisation and augmented notation.
    w = np.array(weights)
    y = [np.array(sample) for sample in samples]
        
    #a = [[0]*len(samples[0]) for i in range(0, classes)]
    a = [[-0.5,0.0,1.5],
         [-3.0,1.5,0.0],
         [0.5,1.5,1.5]]
    
    g = [0 for i in range(0, classes)]
    
    for epoch in range(1, epochs + 1):
        print("Epoch %i - sequential multiclass perceptron learning algorithm" % epoch)
        for k in range(0, len(y)):
            for i in range(0,len(a)):
                g[i] = np.matmul(np.transpose(a[i]),y[k]) 
            j = 0
            max_g = max(g)
            
            for i,gi in enumerate(g):
                if(gi == max_g):
                    j = i
                    break
            
            print(" > at: %s, yt: %s, g: %s, j: %s, w: %s"
                  % (str(np.array(a)), str(np.array(y[k])), str(np.array(g)), str(j+1), str(w[k])))
            
            if((j+1) != w[k]):
                # update weights 
                a[w[k]-1] = a[w[k]-1] + learning_rate * y[k]
                a[j] = a[j] - learning_rate * y[k]
                
        print("")
    

In [3]:
sequential_multi_class_perceptron_learning_algorithm(weights, samples)


Epoch 1 - sequential multiclass perceptron learning algorithm
 > at: [[-0.5  0.   1.5]
 [-3.   1.5  0. ]
 [ 0.5  1.5  1.5]], yt: [1. 0. 1.], g: [ 1. -3.  2.], j: 3, w: 1
 > at: [[ 0.5  0.   2.5]
 [-3.   1.5  0. ]
 [-0.5  1.5  0.5]], yt: [1. 1. 0.], g: [ 0.5 -1.5  1. ], j: 3, w: 1
 > at: [[ 1.5  1.   2.5]
 [-3.   1.5  0. ]
 [-1.5  0.5  0.5]], yt: [1.  0.5 1.5], g: [ 5.75 -2.25 -0.5 ], j: 1, w: 2
 > at: [[ 0.5  0.5  1. ]
 [-2.   2.   1.5]
 [-1.5  0.5  0.5]], yt: [1. 1. 1.], g: [ 2.   1.5 -0.5], j: 1, w: 2
 > at: [[-0.5 -0.5  0. ]
 [-1.   3.   2.5]
 [-1.5  0.5  0.5]], yt: [ 1.  -0.5  0. ], g: [-0.25 -2.5  -1.75], j: 1, w: 3

